### ISSUE TITLE
accumulo start-up fails

### ISSUE THREAD

**Issue by amirhakim** [apache/fluo-uno#176]
Using Ubuntu 17.10
Suddenly started running into issues:
```Unable to start TServer
	org.apache.thrift.transport.TTransportException: Unable to create server on addresses: [localhost:10001]
		at org.apache.accumulo.server.rpc.TServerUtils.startTServer(TServerUtils.java:533)
		at org.apache.accumulo.server.rpc.TServerUtils.startTServer(TServerUtils.java:485)
		at org.apache.accumulo.server.rpc.TServerUtils.startServer(TServerUtils.java:152)
		at org.apache.accumulo.master.Master.run(Master.java:1275)
		at org.apache.accumulo.master.Master.main(Master.java:1434)
		at org.apache.accumulo.master.MasterExecutable.execute(MasterExecutable.java:33)
		at org.apache.accumulo.start.Main$1.run(Main.java:120)
		at java.lang.Thread.run(Thread.java:748)```

**Comment by mikewalch** [comment]
It looks like an Accumulo master might already be running on your machine. You should kill that process or run `uno kill` then run `uno setup accumulo` again.  If that doesn't work, can you give me more information on your setup? What version of Accumulo are you running?

**Comment by ctubbsii** [comment]
Closing this. Cannot reproduce and no response from reporter in 45 days.
