### ISSUE TITLE
Accumulo setup fails on version 1.10.1

### ISSUE THREAD

**Issue by milleruntime** [apache/fluo-uno#277]
Uno fails to setup Accumulo for release 1.10.1. Seems to be a conflict between Guava versions.
<pre>
2021-12-02 11:37:57,942 [start.Main] ERROR: Thread 'org.apache.accumulo.master.state.SetGoalState' died.
java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, java.lang.Object)'
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1380)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1361)
        at org.apache.hadoop.conf.Configuration.setClass(Configuration.java:2740)
        at org.apache.hadoop.ipc.RPC.setProtocolEngine(RPC.java:205)
        at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithAlignmentContext(NameNodeProxiesClient.java:357)
        at org.apache.hadoop.hdfs.NameNodeProxiesClient.createNonHAProxyWithClientProtocol(NameNodeProxiesClient.java:348)
        at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:140)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:374)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:308)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:184)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3414)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:158)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3474)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3442)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.accumulo.core.volume.VolumeImpl.<init>(VolumeImpl.java:45)
        at org.apache.accumulo.core.volume.VolumeConfiguration.create(VolumeConfiguration.java:161)
        at org.apache.accumulo.server.fs.VolumeManagerImpl.get(VolumeManagerImpl.java:357)
        at org.apache.accumulo.server.fs.VolumeManagerImpl.get(VolumeManagerImpl.java:339)
        at org.apache.accumulo.server.fs.VolumeManagerImpl.get(VolumeManagerImpl.java:333)
        at org.apache.accumulo.master.state.SetGoalState.main(SetGoalState.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.accumulo.start.Main$2.run(Main.java:170)
        at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
Versions configured:

- export HADOOP_VERSION=${HADOOP_VERSION:-3.3.0}
- export ZOOKEEPER_VERSION=${ZOOKEEPER_VERSION:-3.7.0}
- export ACCUMULO_VERSION=${ACCUMULO_VERSION:-1.10.1}

**Comment by milleruntime** [comment]
This is probably not a bug, just requirements of different versions. It works fine with older Hadoop and ZK.

- export HADOOP_VERSION=${HADOOP_VERSION:-2.9.2}
- export ZOOKEEPER_VERSION=${ZOOKEEPER_VERSION:-3.6.3}

**Comment by milleruntime** [comment]
I am not sure why this didn't get caught in the version checks in `conf/uno.conf`.
<pre>
if [[ -z $ACCUMULO_REPO && ${ACCUMULO_VERSION} =~ ^1[.][0-9][.][0-9]+$ && ! ${HADOOP_VERSION} = 2.* ]]; then
   echo "ERROR from uno.conf : When using Accumulo versions prior to 1.10.x, expect Hadoop 2.x not $HADOOP_VERSION" 1>&2
   exit 1
fi
</pre>

**Comment by Manno15** [comment]
That check seems to only look for versions prior 1.10.x, not including it. By that logic, 1.10.1 should work with hadoop 3.3.0

**Comment by Manno15** [comment]
I was having trouble getting setup to work on the official tar for 1.10.1 but when building a new one on the rel/1.10.1 branch, setup worked properly for me. 1.10.1 with hadoop 3.3.0 and zookeeper 3.7.0. Additionally, setup worked correctly on 1.10.2-SNAPSHOT.

**Comment by ctubbsii** [comment]
1.10 builds for Hadoop 2.x by default I think. I think you have to build 1.10 specifically with the profile for Hadoop 3 for it to work. This is probably not a problem with 1.10.2-SNAPSHOT because uno is adding `-Dhadoop.profile=3` specifically to the snapshot build it does, whereas 1.10.1 is a release that was built with the default profile (for Hadoop 2). Try rebuilding 1.10.1 using `-Dhadoop.profile=3` and using that... my guess is that it will work fine.

**Comment by ctubbsii** [comment]
I'm going to assume that following the recommendation in my last comment resolves this. If not, please re-open this.
